# Generated by Django 4.1.7 on 2023-07-17 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20)),
                ('contato', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('email2', models.EmailField(blank=True, max_length=250)),
                ('data_criacao', models.DateField(verbose_name='Data do cadastro')),
                ('data_ultimo', models.DateField(verbose_name='Ultima atividade')),
                ('obs', models.TextField(blank=True)),
                ('criador', models.ForeignKey(blank=True, on_delete=models.SET(''), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20)),
                ('contato', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('email2', models.EmailField(blank=True, max_length=250)),
                ('data_criacao', models.DateField(verbose_name='Data do cadastro')),
                ('data_ultimo', models.DateField(verbose_name='Ultima atividade')),
                ('obs', models.TextField(blank=True)),
                ('criador', models.ForeignKey(blank=True, on_delete=models.SET(''), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(verbose_name='Criação')),
                ('data_ultimo', models.DateTimeField(verbose_name='Ultima atividade')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('quantidade', models.IntegerField(blank=True, default=0)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('parcelas', models.IntegerField(blank=True, default=1)),
                ('obs', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.clientes')),
                ('criador', models.ForeignKey(blank=True, on_delete=models.SET(''), to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('pn', models.CharField(blank=True, max_length=200)),
                ('unidade', models.CharField(blank=True, choices=[('Un', 'Unidade'), ('Cx', 'Caixa'), ('Pc', 'Peça'), ('Pt', 'Pacote'), ('Kt', 'Kit'), ('Kg', 'Quilo'), ('Gr', 'Grama'), ('Mt', 'Metro'), ('Cm', 'Centimetro')], max_length=3)),
                ('valor_fornecedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data_criacao', models.DateField(verbose_name='Data do cadastro')),
                ('data_ultimo', models.DateField(verbose_name='Ultima atividade')),
                ('obs', models.TextField(blank=True)),
                ('criador', models.ForeignKey(blank=True, on_delete=models.SET(''), to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegOrcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('fornecedor', models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.fornecedores')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orcamento.orcamentos')),
                ('produto', models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='orcamento.statusorcamento'),
        ),
    ]
