# Generated by Django 4.1.7 on 2023-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regorcamentos',
            old_name='valor_custo',
            new_name='valor_fornecedor',
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='margem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
