# Generated by Django 4.1.7 on 2023-07-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=200)),
                ('ultimo_nome', models.CharField(max_length=200)),
                ('colaborador_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de aniversario')),
                ('data_inicio', models.DateTimeField(verbose_name='Dadta de inicio')),
                ('setor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.setores')),
            ],
        ),
    ]
