# Generated by Django 4.1.7 on 2023-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='data_inicio',
            field=models.DateField(verbose_name='Dadta de inicio'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de aniversario'),
        ),
    ]
